export const FilterData = [
  {
    id: 0,
    name: "Runnning",
    icon: "run",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    date: "09 mai",
    heure: "14:00-16:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 1,
    name: "Soccer",
    icon: "soccer",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    sport: "Baseball",
    date: "14 fevrier",
    heure: "10:00-14:00",
    addess: "20 Boulevard Hellas",
    city: "Paris",
    cp: "75005",
    nbParticipated: 5,
  },
  {
    id: 2,
    name: "Tennis",
    icon: "tennis",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    sport: "Rugby",
    date: "02 mars",
    heure: "16:00-20:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 3,
    name: "Basketball",
    icon: "basketball",
    icon: "surfing",
    userName: "Dany",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    sport: "Soccer",
    date: "10 juin",
    heure: "14:30-16:30",
    addess: "10 Avenue Foch",
    city: "Saint-Denis",
    cp: "93295",
    nbParticipated: 2,
  },
  {
    id: 4,
    name: "Five",
    icon: "lifebuoy",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    date: "09 mai",
    heure: "14:00-16:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 5,
    name: "Fitness",
    icon: "yoga",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    date: "09 mai",
    heure: "14:00-16:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 6,
    name: "Bodybuilding",
    icon: "weight-lifter",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    sport: "Baseball",
    date: "14 fevrier",
    heure: "10:00-14:00",
    addess: "20 Boulevard Hellas",
    city: "Paris",
    cp: "75005",
    nbParticipated: 5,
  },
  {
    id: 7,
    name: "Hiking",
    icon: "hiking",
    userName: "Brand-Fullstack",
    image: require("../../../assets/Images/Home/Homme1.jpg"),

    sport: "Surf",
    date: "01 janvier",
    heure: "09:00-14:00",
    addess: "32 General Leclerc",
    city: "Clichy",
    cp: "92110",
    nbParticipated: 5,
  },
  {
    id: 8,
    name: "Snooker",
    icon: "dots-triangle",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    sport: "Rugby",
    date: "02 mars",
    heure: "16:00-20:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 9,
    name: "Golf",
    icon: "golf",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    date: "09 mai",
    heure: "14:00-16:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 10,
    name: "Cycling",
    icon: "bike",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    sport: "Rugby",
    date: "02 mars",
    heure: "16:00-20:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 11,
    name: "Boxing",
    icon: "boxing-glove",
    userName: "Brand-Fullstack",
    image: require("../../../assets/Images/Home/Homme1.jpg"),

    sport: "Surf",
    date: "01 janvier",
    heure: "09:00-14:00",
    addess: "32 General Leclerc",
    city: "Clichy",
    cp: "92110",
    nbParticipated: 5,
  },
  {
    id: 12,
    name: "Dance",
    icon: "human-female-dance",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    sport: "Rugby",
    date: "02 mars",
    heure: "16:00-20:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 13,
    name: "Table tennis",
    icon: "table-tennis",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    sport: "Baseball",
    date: "14 fevrier",
    heure: "10:00-14:00",
    addess: "20 Boulevard Hellas",
    city: "Paris",
    cp: "75005",
    nbParticipated: 5,
  },
  {
    id: 14,
    name: "Baseball",
    icon: "baseball",
    userName: "Dany",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    sport: "Soccer",
    date: "10 juin",
    heure: "14:30-16:30",
    addess: "10 Avenue Foch",
    city: "Saint-Denis",
    cp: "93295",
    nbParticipated: 2,
  },
  {
    id: 15,
    name: "Ski",
    icon: "ski",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    sport: "Baseball",
    date: "14 fevrier",
    heure: "10:00-14:00",
    addess: "20 Boulevard Hellas",
    city: "Paris",
    cp: "75005",
    nbParticipated: 5,
  },
  {
    id: 16,
    name: "Surf",
    icon: "surfing",
    userName: "Dany",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    sport: "Soccer",
    date: "10 juin",
    heure: "14:30-16:30",
    addess: "10 Avenue Foch",
    city: "Saint-Denis",
    cp: "93295",
    nbParticipated: 2,
  },
  {
    id: 17,
    name: "Rugby",
    icon: "rugby",
    userName: "Brand-Fullstack",
    image: require("../../../assets/Images/Home/Homme1.jpg"),

    sport: "Surf",
    date: "01 janvier",
    heure: "09:00-14:00",
    addess: "32 General Leclerc",
    city: "Clichy",
    cp: "92110",
    nbParticipated: 5,
  },
  {
    id: 18,
    name: "Soccer",
    icon: "soccer",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    sport: "Rugby",
    date: "02 mars",
    heure: "16:00-20:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 19,
    name: "Tennis",
    icon: "tennis",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    date: "09 mai",
    heure: "14:00-16:00",
    addess: "2 Square Vendetta",
    city: "Paris",
    cp: "75015",
    nbParticipated: 4,
  },
  {
    id: 20,
    name: "Basketball",
    icon: "basketball",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    sport: "Baseball",
    date: "14 fevrier",
    heure: "10:00-14:00",
    addess: "20 Boulevard Hellas",
    city: "Paris",
    cp: "75005",
    nbParticipated: 5,
  },
];

export const filterData2 = [
  {
    name: "Fast food",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/chicken.png",
    id: "0",
  },
  {
    name: "Burgers",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/macdo.png",
    id: "1",
  },
  {
    name: "Salads",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/nandos.png",
    id: "2",
  },
  {
    name: "Hotdog",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/pizza.png",
    id: "3",
  },
  {
    name: "Chinese",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/pizza6.png",
    id: "4",
  },
  {
    name: "Mexican",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/plate1.png",
    id: "5",
  },
  {
    name: "Sea food",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/plate2.png",
    id: "6",
  },
  {
    name: "Chinese Food",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/plate3.png",
    id: "7",
  },
  {
    name: "Mexican pie",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/plate4.png",
    id: "8",
  },
  {
    name: "Ocean dish",
    image: "https://bukasapics.s3.us-east-2.amazonaws.com/plate5.png",
    id: "9",
  },
];

export const SportsList = [
  {
    id: 0,
    name: "All",
    icon: "all-inclusive",
  },
  {
    id: 1,
    name: "Runnning",
    icon: "run",
  },
  {
    id: 2,
    name: "Soccer",
    icon: "soccer",
  },
  {
    id: 3,
    name: "Tennis",
    icon: "tennis",
  },
  {
    id: 4,
    name: "Basketball",
    icon: "basketball",
  },
  {
    id: 5,
    name: "Five",
    icon: "lifebuoy",
  },
  {
    id: 6,
    name: "Fitness",
    icon: "yoga",
  },
  {
    id: 7,
    name: "Bodybuilding",
    icon: "weight-lifter",
  },
  {
    id: 8,
    name: "Hiking",
    icon: "hiking",
  },
  {
    id: 9,
    name: "Snooker",
    icon: "dots-triangle",
  },
  {
    id: 10,
    name: "Golf",
    icon: "golf",
  },
  {
    id: 11,
    name: "Cycling",
    icon: "bike",
  },
  {
    id: 12,
    name: "Boxing",
    icon: "boxing-glove",
  },
  {
    id: 13,
    name: "Dance",
    icon: "human-female-dance",
  },
  {
    id: 14,
    name: "Table tennis",
    icon: "table-tennis",
  },
  {
    id: 15,
    name: "Baseball",
    icon: "baseball",
  },
  {
    id: 16,
    name: "Ski",
    icon: "ski",
  },
  {
    id: 17,
    name: "Surf",
    icon: "surfing",
  },
  {
    id: 18,
    name: "Rugby",
    icon: "rugby",
  },
  {
    id: 19,
    name: "Soccer",
    icon: "soccer",
  },
  {
    id: 20,
    name: "Tennis",
    icon: "tennis",
  },
  {
    id: 21,
    name: "Basketball",
    icon: "basketball",
  },
];

export const ArticalesData = [
  {
    id: 1,
    title: "Sport",
    articale:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliguip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum",
    image: require("../../../assets/Images/Home/image5.jpeg"),
    like: 10,
    numberComments: 2,
    comments: [
      {
        id: 1,
        comment: "Merci beaucoup",
      },
      // {
      //   id: 2,
      //   comment: "Je vais m'y mettre",
      // },
    ],
  },

  {
    id: 2,
    title: "Yoga",
    articale:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliguip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum",
    image: require("../../../assets/Images/Home/image1.jpg"),
    like: 3,
    numberComments: 4,
    comments: [
      {
        id: 1,
        comment: "Merci beaucoup",
      },
      // {
      //   id: 2,
      //   comment: "J'ai pris note",
      // },
      // {
      //   id: 3,
      //   comment: "Je vais m'y mettre",
      // },
      // {
      //   id: 4,
      //   comment: "Vous me donnez vraiment envi d'y aller",
      // },
    ],
  },
  {
    id: 3,
    title: "Nutrition",
    articale:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliguip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum",
    image: require("../../../assets/Images/Home/image2.jpg"),
    like: 10,
    numberComments: 2,
    comments: [
      {
        id: 1,
        comment: "Merci beaucoup",
      },
      // {
      //   id: 2,
      //   comment: "Je vais m'y mettre",
      // },
    ],
  },
  {
    id: 4,
    title: "Rest",
    articale:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliguip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum",
    image: require("../../../assets/Images/Home/image4.jpg"),
    like: 10,
    numberComments: 2,
    comments: [
      {
        id: 1,
        comment: "Merci beaucoup",
      },
      // {
      //   id: 2,
      //   comment: "Je vais m'y mettre",
      // },
    ],
  },
  {
    id: 5,
    title: "Sport",
    articale:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua ut enim adminim veniam, quis nostrud exercitation ullamco laboris nisi utaliguip ex ea commodo consequat. Duis aute irure dolor inreprehenderit in voluptate velit esse cillum",
    image: require("../../../assets/Images/Home/image5.jpeg"),
    like: 10,
    numberComments: 2,
    comments: [
      {
        id: 1,
        comment: "Merci beaucoup",
      },
      // {
      //   id: 2,
      //   comment: "Je vais m'y mettre",
      // },
    ],
  },
];

export const AttendeesList = [
  {
    id: "1",
    userName: "Brand-Fullstack",
    image: require("../../../assets/Images/Home/Homme1.jpg"),
    city: "Clichy",
    icon: "soccer",
    message: "Lorem ipsum dolor",
    hour: "15:33",
  },
  {
    id: "2",
    userName: "Lionel-Fullstack",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    city: "Bondy",
    icon: "basketball",
    message: "Lorem ipsum dolor",
    hour: "17:23",
  },
  {
    id: "3",
    userName: "Binjamin-",
    image: require("../../../assets/Images/Home/Homme3.jpg"),
    city: "Cachan",
    icon: "yoga",
    message: "Lorem ipsum dolor",
    hour: "17:29",
  },
  {
    id: "4",
    userName: "Dany",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    city: "Clichy",
    icon: "tennis",
    message: "Lorem ipsum dolor",
    hour: "17:33",
  },
  {
    id: "5",
    userName: "Marc",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    city: "Sain-ouin",
    icon: "weight-lifter",
    message: "Lorem ipsum dolor",
    hour: "18:00",
  },
  {
    id: "6",
    userName: "Suzie",
    image: require("../../../assets/Images/Home/Femme2.jpg"),
    city: "Nancy",
    icon: "ski",
    message: "Lorem ipsum dolor",
    hour: "18:33",
  },
  {
    id: "7",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "18:33",
  },
  {
    id: "8",
    userName: "Luc",
    image: require("../../../assets/Images/Home/Homme2.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "18:41",
  },
  {
    id: "9",
    userName: "Fleure",
    image: require("../../../assets/Images/Home/Femme2.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "18:43",
  },
  {
    id: "10",
    userName: "Ericka",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "19:03",
  },
  {
    id: "11",
    userName: "Karl",
    image: require("../../../assets/Images/Home/Homme1.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "19:23",
  },
  {
    id: "12",
    userName: "Oceane",
    image: require("../../../assets/Images/Home/Femme1.jpg"),
    city: "Rouan",
    icon: "surfing",
    message: "Lorem ipsum dolor",
    hour: "19:33",
  },
];
